# Generated by Django 3.0.7 on 2020-07-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'ordering': ['nombre'], 'verbose_name': 'articulo', 'verbose_name_plural': 'articulos'},
        ),
        migrations.AlterModelOptions(
            name='familia',
            options={'ordering': ['familia']},
        ),
        migrations.AlterModelOptions(
            name='medida',
            options={'ordering': ['medida']},
        ),
        migrations.AddField(
            model_name='articulos',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Descuento ', max_digits=8),
        ),
        migrations.AddField(
            model_name='articulos',
            name='fecha_caducidad',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='articulos',
            name='fecha_empieza_publicacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio_articulo',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Precio unitario', max_digits=8),
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio_envio',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Precio envío', max_digits=6),
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio_mayoreo',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Precio mayoreo', max_digits=8),
        ),
        migrations.AddField(
            model_name='articulos',
            name='tipo_descuento',
            field=models.CharField(choices=[('s', 'Sin descuento'), ('p', 'Porcentaje'), ('v', 'Valor')], default='s', help_text='Tipos de descuento', max_length=1),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='Descrip_larga',
            field=models.CharField(blank=True, help_text='Descripción', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Alta del artículo'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='descrip_corta',
            field=models.CharField(blank=True, help_text='Pequeña descripción', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='estado_articulo',
            field=models.CharField(choices=[('0', 'Por autorizar'), ('a', 'Autorizado'), ('b', 'baja')], default='0', help_text='Situación del artículo', max_length=1),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='familia',
            field=models.ForeignKey(blank=True, help_text='Familia', on_delete=django.db.models.deletion.CASCADE, to='articulos.Familia'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='imagen_articulo',
            field=models.ImageField(help_text='Imagen del artículo', upload_to=''),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='medida',
            field=models.ForeignKey(help_text='Unidad de medida', on_delete=django.db.models.deletion.CASCADE, to='articulos.Medida'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre del artículo', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='nota_rechazo',
            field=models.CharField(help_text='Nota de rechazo de publicación', max_length=200),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, help_text='Ultima modificación del artículo'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='familia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medida',
            name='medida',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
