# Generated by Django 3.0.7 on 2020-07-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20200708_0254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulos',
            new_name='Articulos1',
        ),
        migrations.RenameModel(
            old_name='Familia',
            new_name='Familia1',
        ),
        migrations.RenameModel(
            old_name='Medida',
            new_name='Medida1',
        ),
    ]
